### ISSUE TITLE
Documentation of why hash64 returns two values

### ISSUE THREAD

**Issue by dan-blanchard** [hajimes/mmh3#8]
As a user it is very confusing why `mmh3.hash64` returns two 64-bit values, whereas `hash` and `hash128` do not. Are we supposed to just pick one of them? Is there a recommended way to combine them?

**Comment by hajimes** [comment]
Thank you so much for being interested in this library. The reason is fairly simple: it uses the 128 bit version of MurmurHash3 as its backend.

I thought for this kind of library efficiency has higher priority than interface consistency. But your suggestion has a point and I'll add warning to README to lessen confusion.
